name: "Dependabot Automerge"

on:
  workflow_run:
    workflows: ["Android Kit Pull Request Checks"]
    types:
      - completed

jobs:
  pr-check:
    name: "Dependabot Automerge"
    uses: mParticle/mparticle-workflows/.github/workflows/dependabot-automerge.yml@fix/SQDSDKS-4228
